#!/usr/bin/env python

import sys

from rqt_gui.main import Main
from rqt_pr2_dashboard.pr2_dashboard import PR2Dashboard

plugin = 'rqt_pr2_dashboard.pr2_dashboard.PR2Dashboard'
main = Main()
sys.exit(main.main(standalone=plugin, plugin_argument_provider=PR2Dashboard.add_arguments))
